### ISSUE TITLE
Read text from multi line textbox

### ISSUE THREAD

**Issue by tanphamanhh** [airpptx/airppt-parser#2]
I run the parser and it's only read the first line of the textbox if the textboxt has more than one line.
And if the paragraph has more text style like this:
" **Visual Studio Code** is a lightweight **_but powerful source code editor_** which runs on your desktop and is available for Windows, macOS and Linux."
may be the color of the text, the font size too. I cant get all of this

**Comment by rlingineni** [comment]
Looks like there are a few questions here.  I'll get them separately. Here's the example of what I'm trying to parse based on your example.

![image](https://user-images.githubusercontent.com/5509813/48960494-efbe8580-ef21-11e8-92a0-0d1fe939a320.png)

## Multi-line Problem

Thanks, I hadn't realized this. The problem can be fixed in the [paragraph parser](https://github.com/airpptx/airppt-parser/blob/f93844d20e455a6eb84a39237ab61f521cad2df3/ts/parsers/paragraphparser.ts#L16)

I naively just looked at the first element when extracting text, but after diseccting the actual Powerpoint Element, I see that each newline is a separate element of the array. 

There is a `raw` element that is also a part of the PPTElement that actually has the parsed PPT XML that helps when debugging this uncaught stuff.

![image](https://user-images.githubusercontent.com/5509813/48960590-a1f64d00-ef22-11e8-94b4-0bee1abf41a1.png)


Might be smarter to iterate the array length and concatenate all of the text, each one is separate because of the different text properties like bolding.

```javascript
text: textElement["a:r"][0]["a:t"].toString() // problem is with the 0.
```

I'll see if I can push a new version soon or I'd encourage you to make a PR, now that you know the problem. However, it seems that each break  😄  

## Preserving Color
I used red, and my color was preserved by the way. Colors are weird in Powerpoint, they can come from the theme or designs, try to explicitly assign one.

``` javascript
"textCharacterProperties": {
          "size": 1200, //ppt multipes fonts by 100 btw
          "fontAttributes": [
            0
          ],
          "font": "Helvetica", //this is the default, read the paragraph parser code, it'll teach you better
          "fillColor": "FF0000"
        }
```

## In-line Bolding and Italics
I'm not sure how to handle the bolding and italics embedded in the text just yet, or how to display that information, so that's probably not supported. Each `<a:r>` element has the text highlighting and stuff, but it's hard to return that information in one easy way.


I'm still writing some docs, I haven't officially "published" this yet.  Not all elements are supported, you can see that list [kind of here](https://github.com/rlingineni/airppt/wiki#supported-items). But the goal is that contributors can extend it as needed. Thank you for using and opening an issue.

**Comment by rlingineni** [comment]
@tanphamanhh, should be fixed. Just published 1.0.6

**Comment by tanphamanhh** [comment]
I have an example PPTX that in one shape, it have more paragraphs. you can see the object model of pptx in here
![documentobjectmodel_img1](https://user-images.githubusercontent.com/16513227/48963842-526d5b00-efce-11e8-8a21-a4f43ca336db.png)

I see in your `PowerpointElement`, in one shape it only have one paragraph
![capture2](https://user-images.githubusercontent.com/16513227/48963833-336ec900-efce-11e8-89b2-df55a41a8297.PNG)
But, like the PPTX Object model image you see above, in one shape (`PowerpointElement`), it can have more than one paragraph.
Here is my pptx file's raw data:
![capture](https://user-images.githubusercontent.com/16513227/48963851-8b0d3480-efce-11e8-8e0c-72774db3fc90.PNG)
In this [a:p] data, it has 2 paragraphs

**Comment by rlingineni** [comment]
That looks like a complex shape. At this point, I don't have plans to support that just yet. Feature requests can be tracked in [Fider](https://airppt.fider.io/). I have added yours.

However, if this is something you really would like, I'd encourage you to make a PR to update the [PPT Model](
https://github.com/airpptx/airppt-models/blob/master/ts/pptelement.ts) and the parser to support paragraphs to return an array instead.
